name: Push screenshot-to-code to GAR

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  GAR_REPO: "gcp-cluster-automation"
  GAR_FOLDER: "screenshot-to-code"
  FRONTEND_IMAGE: "frontend"
  BACKEND_IMAGE: "backend"

jobs:
  push-image:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Clone Target Repository
      - name: Clone Target Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Step 3: Configure Docker for Google Artifact Registry
      - name: Configure Docker for Google Artifact Registry
        run: gcloud --quiet auth configure-docker

      # Step 4: Build and Push Frontend Image
      - name: Build and Push Frontend Image
        run: |
          base_name="${{ env.FRONTEND_IMAGE }}"
          tag_or_digest="v1.0.0"
          new_image="gcr.io/${{ env.GAR_REPO }}/${{ env.GAR_FOLDER }}/${base_name}/${base_name}_${tag_or_digest}"
          
          echo "Building and tagging frontend image as $new_image"
          docker build -t local-frontend:${tag_or_digest} ./frontend
          docker tag local-frontend:${tag_or_digest} $new_image
          docker push $new_image

      # Step 5: Build and Push Backend Image
      - name: Build and Push Backend Image
        run: |
          base_name="${{ env.BACKEND_IMAGE }}"
          tag_or_digest="v1.0.0"
          new_image="gcr.io/${{ env.GAR_REPO }}/${{ env.GAR_FOLDER }}/${base_name}/${base_name}_${tag_or_digest}"
          
          echo "Building and tagging backend image as $new_image"
          docker build -t local-backend:${tag_or_digest} ./backend
          docker tag local-backend:${tag_or_digest} $new_image
          docker push $new_image
